export enum HEADERS {
  FECHA_FACTURA,
  NUMERO_FACTURA,
  RAZON_SOCIAL,
  VALOR_TOTAL_FACTURA,
}

export enum BODY {
  CODIGO_PRODUCTO, //
  ITEM_DESCRIPCION_PRODUCTO, //
  TIPO_EMBALAJE, //
  UNIDADES_EMBALAJE, //
  UNIDADES_VENDIDAS, //
  VALOR_VENTA_ITEM, //
  VALOR_IBUA_Y_OTROS,
  VALOR_UNITARIO_ITEM, 

  TOTAL_FACTURA_SIN_IVA,
  PACKS_VENDIDOS,
  VALOR_VENTA_ITEM_TOTAL_NC,
  VALOR_DESCUENTO_ITEM,
  APLICA_IVA_ITEM,

  ES_DEVOLUCION,

  PACKS_CON_UNIDADES,
}
