export enum StickerStatus {
  PENDING = 'PENDING_VALIDATION',
  IN_CAPTURE = 'IN_CAPTURE',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
  NO_PROCESABLE = 'NO_PROCESABLE',
}
