import { Fields } from '../../enums/fields';

export enum AjeHeaderFields {
  FECHA_FACTURA = Fields.FECHA_FACTURA,
  NUMERO_FACTURA = Fields.NUMERO_FACTURA,
  VALOR_TOTAL_FACTURA = Fields.VALOR_TOTAL_FACTURA,
  TOTAL_FACTURA_SIN_IVA = Fields.TOTAL_FACTURA_SIN_IVA,
  RAZON_SOCIAL = Fields.RAZON_SOCIAL,
  TOTAL_UNIDADES = Fields.TOTAL_UNIDADES,
  TOTAL_PACAS = Fields.TOTAL_PACAS,
  FECHA_VENCIMIENTO = Fields.FECHA_VENCIMIENTO,
}

export enum AjeBodyFields {
  CODIGO_PRODUCTO = Fields.CODIGO_PRODUCTO,
  ITEM_DESCRIPCION_PRODUCTO = Fields.ITEM_DESCRIPCION_PRODUCTO,
  TIPO_EMBALAJE = Fields.TIPO_EMBALAJE,
  PACKS_VENDIDOS = Fields.PACKS_VENDIDOS,
  UNIDADES_VENDIDAS = Fields.UNIDADES_VENDIDAS,
  VALOR_VENTA_ITEM = Fields.VALOR_VENTA_ITEM,
  UNIDADES_EMBALAJE = Fields.UNIDADES_EMBALAJE,
  PRECIO_ANTES_IVA = Fields.PRECIO_ANTES_IVA,
  VALOR_DESCUENTO_ITEM = Fields.VALOR_DESCUENTO,
  VALOR_IVA = Fields.VALOR_IVA,
}

export const AJE_THRESOLDS = {
  [AjeHeaderFields.FECHA_FACTURA]: 0.9,
  [AjeHeaderFields.NUMERO_FACTURA]: 0.85,
  [AjeHeaderFields.TOTAL_FACTURA_SIN_IVA]: 0.95,
  [AjeHeaderFields.VALOR_TOTAL_FACTURA]: 0.95,
  [AjeHeaderFields.RAZON_SOCIAL]: 0.95,
  [AjeBodyFields.CODIGO_PRODUCTO]: 0.9,
  [AjeBodyFields.ITEM_DESCRIPCION_PRODUCTO]: 0.9,
  [AjeBodyFields.TIPO_EMBALAJE]: 0.95,
  [AjeBodyFields.PACKS_VENDIDOS]: 0.85,
  [AjeBodyFields.UNIDADES_VENDIDAS]: 0.9,
  [AjeBodyFields.VALOR_VENTA_ITEM]: 0.95,
  [AjeBodyFields.UNIDADES_EMBALAJE]: 0.9,
  [AjeBodyFields.PRECIO_ANTES_IVA]: 0.95,
  [AjeBodyFields.VALOR_DESCUENTO_ITEM]: 0.8,
  [AjeBodyFields.VALOR_IVA]: 0.9,
};
