import { Fields } from "../../enums/fields";

export enum FemsaHeaderFields {
  FECHA_FACTURA = Fields.FECHA_FACTURA,
  NUMERO_FACTURA = Fields.NUMERO_FACTURA,
  VALOR_TOTAL_FACTURA = Fields.VALOR_TOTAL_FACTURA,
  RAZON_SOCIAL = Fields.RAZON_SOCIAL,
  TOTAL_FACTURA_SIN_IVA = Fields.TOTAL_FACTURA_SIN_IVA,
  IVA_TARIFA_GENERAL = Fields.IVA_TARIFA_GENERAL,
  IBUA = Fields.IBUA,
}

export enum FemsaBodyFields {
  CODIGO_PRODUCTO = Fields.CODIGO_PRODUCTO,
  ITEM_DESCRIPCION_PRODUCTO = Fields.ITEM_DESCRIPCION_PRODUCTO,
  TIPO_EMBALAJE = Fields.TIPO_EMBALAJE,
  UNIDADES_VENDIDAS = Fields.UNIDADES_VENDIDAS,
  VALOR_UNITARIO_ITEM = Fields.VALOR_UNITARIO_ITEM,
  VALOR_VENTA_ITEM = Fields.VALOR_VENTA_ITEM,
  VALOR_IBUA_Y_OTROS = Fields.VALOR_IBUA_Y_OTROS,
  UNIDADES_EMBALAJE = Fields.UNIDADES_EMBALAJE,
  CANTIDAD = Fields.CANTIDAD,
  VALOR_DESCUENTO = Fields.VALOR_DESCUENTO,
}

export const FEMSA_THRESOLDS = {
  [FemsaHeaderFields.FECHA_FACTURA]: 0.95,
  [FemsaHeaderFields.NUMERO_FACTURA]: 0.97,
  [FemsaHeaderFields.VALOR_TOTAL_FACTURA]: 0.88,
  [FemsaHeaderFields.RAZON_SOCIAL]: 0.99,
  [FemsaHeaderFields.TOTAL_FACTURA_SIN_IVA]: 0.88,
  [FemsaBodyFields.CODIGO_PRODUCTO]: 0.95,
  [FemsaBodyFields.ITEM_DESCRIPCION_PRODUCTO]: 0.92,
  [FemsaBodyFields.UNIDADES_VENDIDAS]: 0.83,
  [FemsaBodyFields.UNIDADES_EMBALAJE]: 0.85,
  [FemsaBodyFields.TIPO_EMBALAJE]: 0.88,
  [FemsaBodyFields.VALOR_UNITARIO_ITEM]: 0.93,
  [FemsaBodyFields.VALOR_VENTA_ITEM]: 0.9,
  [FemsaBodyFields.VALOR_IBUA_Y_OTROS]: 0.89,
};
