import { Fields } from "../../enums/fields";

export enum CokeHeaderFields {
  FECHA_FACTURA = Fields.FECHA_FACTURA,
  NUMERO_FACTURA = Fields.NUMERO_FACTURA,
  RAZON_SOCIAL = Fields.RAZON_SOCIAL,
  VALOR_TOTAL_FACTURA = Fields.VALOR_TOTAL_FACTURA,
}

export enum CokeBodyFields {
  CODIGO_PRODUCTO = Fields.CODIGO_PRODUCTO,
  ITEM_DESCRIPCION_PRODUCTO = Fields.ITEM_DESCRIPCION_PRODUCTO,
  TIPO_EMBALAJE = Fields.TIPO_EMBALAJE,
  UNIDADES_VENDIDAS = Fields.UNIDADES_VENDIDAS,
  VALOR_VENTA_ITEM = Fields.VALOR_VENTA_ITEM,
  VALOR_IBUA_Y_OTROS = Fields.VALOR_IBUA_Y_OTROS,
  UNIDADES_EMBALAJE = Fields.UNIDADES_EMBALAJE,
  VALOR_UNITARIO_ITEM = Fields.VALOR_UNITARIO_ITEM,
}

export const COKE_THRESOLDS = {
  [CokeHeaderFields.FECHA_FACTURA]: 0.96,
  [CokeHeaderFields.NUMERO_FACTURA]: 0.94,
  [CokeHeaderFields.RAZON_SOCIAL]: 0.99,
  [CokeHeaderFields.VALOR_TOTAL_FACTURA]: 0.93,
  [CokeBodyFields.CODIGO_PRODUCTO]: 0.46,
  [CokeBodyFields.ITEM_DESCRIPCION_PRODUCTO]: 0.8,
  [CokeBodyFields.TIPO_EMBALAJE]: 0.44,
  [CokeBodyFields.UNIDADES_VENDIDAS]: 0.41,
  [CokeBodyFields.VALOR_VENTA_ITEM]: 0.87,
  [CokeBodyFields.VALOR_IBUA_Y_OTROS]: 0.43,
  [CokeBodyFields.UNIDADES_EMBALAJE]: 0.45,
};
